server:
    port: 8083
spring:
  application:
    name: likelion-websocket
  ai:
    openai:
      api-key: ${OPEN_API_KEY}
      chat:
        options:
          model: gpt-4.5-turbo
          temperature: 0.7
          max-tokens: 200

